import "./globals.css";
import { Inter } from "next/font/google";
import clsx from "clsx";

import Provider from "@/components/provider";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={clsx(
        inter.className,
        "h-full scroll-smooth antialiased",
        "min-h-screen bg-gray-100 sm:no-scrollbar"
      )}
    >
      <body className="flex h-full flex-col">
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
